{% set version = "0.2.0" %}

package:
  name: ragged
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/ragged/ragged-{{ version }}.tar.gz
  sha256: 0f934e0dab2ff42b98cf38912fd1d375fe0e54c7d155866c65f62c8df096ff9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.24.0
    - awkward >=2.6.7

test:
  imports:
    - ragged
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    # Basic dependency check at runtime
    - python -c "import ragged; print(ragged.array([[1.]]))"

about:
  home: https://github.com/scikit-hep/ragged
  summary: 'Ragged is a library for manipulating ragged arrays as though they were NumPy or CuPy arrays, following the Array API specification.'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
