{% set version = "0.1.0" %}

package:
  name: ragged
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/ragged/ragged-{{ version }}.tar.gz
  sha256: 5c9502b7a2a21c4ebe8ec4c1452c6665bb2fcf11d414626ebec6a43426a37be0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    # Not yet compatible with numpy 2
    # https://github.com/scikit-hep/ragged/pull/60
    - numpy >1.22.0,<2.0a0
    - awkward 2.5

test:
  imports:
    - ragged
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    # https://github.com/scikit-hep/ragged/pull/64
    - python -c "import ragged; print(ragged.array([[1.]]))"

about:
  home: https://github.com/scikit-hep/ragged
  summary: 'Ragged is a library for manipulating ragged arrays as though they were NumPy or CuPy arrays, following the Array API specification.'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
